version: '3.8'

services:

  heavy-mock-http-server:
    image: heavy-mock-http-server:dev
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./examples/single-endpoint.yml
        target: /etc/heavy-mock/config.yml
        read_only: true
