version: '3.8'

services:

  heavy-mock-http-server:
    image: heavy-mock-http-server:dev
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - HEAVY_MOCK_CONFIG=/configs/single-endpoint.yml
    volumes:
      - type: bind
        source: ./examples
        target: /configs
        read_only: true

