name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21.0.3'
          cache: 'maven'
          cache-dependency-path: 'server/pom.xml'
      - name: Build with Maven
        run: |
          cd server
          mvn -B package
      - name: Build Docker image
        run: |
          cd server
          docker build -t heavy-mock-http-server:dev .
