name: Format

on:
  pull_request:
    branches:
      - main
      - develop

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21.0.3'
          cache: 'maven'
          cache-dependency-path: 'server/pom.xml'
      - name: Format Java Files
        run: |
          mvn -f server/pom.xml fmt:check
