name: Server CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:

  maven-format:
    name: Check Java Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21.0.3'
          cache: 'maven'
          cache-dependency-path: 'server/pom.xml'
      - name: Format Java Files
        run: |
          mvn -f server/pom.xml fmt:check

  maven-verify:
    name: Maven Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21.0.3'
          cache: 'maven'
          cache-dependency-path: 'server/pom.xml'
      - name: Maven Verify
        run: |
          mvn -B verify --file server/pom.xml

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t heavy-mock-http-server:dev server
